project:
  title: "sceloporus-cols"
  type: website
  output-dir: docs

website:
  announcement:
    dismissable: false
    position: above-navbar # Keeps it pinned to the very top
    content: "**The 'cost-of-living squeeze' mediates survival in a desert ectotherm**"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Start here
      - href: home-range-estimation.qmd
        text: "Home range estimation"
      - href: resting-metabolic-rates.qmd
        text: "Resting metabolic rates"
      - href: simulations-behavioral-thermoregulation.qmd
        text: "Behavioral thermoregulation simulations"
      - href: feeding-demand.qmd
        text: "COLS as Feeding demand"
      - href: cols-survival.qmd
        text: "Effects of COLS on Survival"
      - icon: github
        href: https://github.com/ggcostoya/sceloporus-cols
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    lightbox: true

knitr:
  opts_chunk:
    dev: png
    dpi: 350



